### ISSUE TITLE
building with --so fails

### ISSUE THREAD

**Issue by shadeware** [scylladb/seastar#467]
Building seastar on ubuntu 18.04 with default gcc-7.3 fails with configure flag `--so` (and succeeds without it).

Error message:
```
[79/199] LINK build/debug/apps/seawreck/seawreck
FAILED: build/debug/apps/seawreck/seawreck 
g++  -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/coding/seastar/build/debug/gen -I/coding/seastar/build/debug/c-ares -Lbuild/debug -Lbuild/debug/fmt/fmt -g -Wl,--no-as-needed  -shared -fvisibility=hidden -Wno-attributes -pthread  -o build/debug/apps/seawreck/seawreck build/debug/apps/seawreck/seawreck.o build/debug/core/reactor.o build/debug/core/alien.o build/debug/core/execution_stage.o build/debug/core/systemwide_memory_barrier.o build/debug/core/fstream.o build/debug/core/posix.o build/debug/core/memory.o build/debug/core/resource.o build/debug/core/scollectd.o build/debug/core/metrics.o build/debug/core/app-template.o build/debug/core/thread.o build/debug/core/dpdk_rte.o build/debug/core/fsqual.o build/debug/core/linux-aio.o build/debug/util/conversions.o build/debug/util/program-options.o build/debug/util/log.o build/debug/util/backtrace.o build/debug/util/alloc_failure_injector.o build/debug/net/packet.o build/debug/net/posix-stack.o build/debug/net/net.o build/debug/net/stack.o build/debug/net/inet_address.o build/debug/rpc/rpc.o build/debug/rpc/lz4_compressor.o build/debug/core/exception_hacks.o build/debug/core/future-util.o build/debug/net/proxy.o build/debug/net/virtio.o build/debug/net/dpdk.o build/debug/net/ip.o build/debug/net/ethernet.o build/debug/net/arp.o build/debug/net/native-stack.o build/debug/net/ip_checksum.o build/debug/net/udp.o build/debug/net/tcp.o build/debug/net/dhcp.o build/debug/net/tls.o build/debug/net/dns.o build/debug/net/config.o -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s  -lyaml-cpp -lcares-seastar -lfmt -lasan -lubsan  
/usr/bin/x86_64-linux-gnu-ld: build/debug/fmt/fmt/libfmt.a(printf.cc.o): relocation R_X86_64_PC32 against symbol `_ZTVN3fmt17BasicMemoryWriterIcSaIcEEE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
I tried adding `set (CMAKE_POSITION_INDEPENDENT_CODE TRUE)` at the start of `fmt/CMakeLists.txt`, and the building went further. It stopped at this next error:
```
[8/120] LINK build/debug/apps/httpd/httpd
FAILED: build/debug/apps/httpd/httpd 
g++  -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_ASAN_ENABLED -O0 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_NO_EXCEPTION_HACK -DSEASTAR_SHUFFLE_TASK_QUEUE -I/coding/seastar/build/debug/gen -I/coding/seastar/build/debug/c-ares -Lbuild/debug -Lbuild/debug/fmt/fmt -g -Wl,--no-as-needed  -shared -fvisibility=hidden -Wno-attributes -pthread  -o build/debug/apps/httpd/httpd build/debug/apps/httpd/main.o build/debug/http/transformers.o build/debug/http/json_path.o build/debug/http/file_handler.o build/debug/http/common.o build/debug/http/routes.o build/debug/json/json_elements.o build/debug/json/formatter.o build/debug/http/matcher.o build/debug/http/mime_types.o build/debug/http/httpd.o build/debug/http/reply.o build/debug/http/api_docs.o build/debug/net/proxy.o build/debug/net/virtio.o build/debug/net/dpdk.o build/debug/net/ip.o build/debug/net/ethernet.o build/debug/net/arp.o build/debug/net/native-stack.o build/debug/net/ip_checksum.o build/debug/net/udp.o build/debug/net/tcp.o build/debug/net/dhcp.o build/debug/net/tls.o build/debug/net/dns.o build/debug/net/config.o build/debug/core/reactor.o build/debug/core/alien.o build/debug/core/execution_stage.o build/debug/core/systemwide_memory_barrier.o build/debug/core/fstream.o build/debug/core/posix.o build/debug/core/memory.o build/debug/core/resource.o build/debug/core/scollectd.o build/debug/core/metrics.o build/debug/core/app-template.o build/debug/core/thread.o build/debug/core/dpdk_rte.o build/debug/core/fsqual.o build/debug/core/linux-aio.o build/debug/util/conversions.o build/debug/util/program-options.o build/debug/util/log.o build/debug/util/backtrace.o build/debug/util/alloc_failure_injector.o build/debug/net/packet.o build/debug/net/posix-stack.o build/debug/net/net.o build/debug/net/stack.o build/debug/net/inet_address.o build/debug/rpc/rpc.o build/debug/rpc/lz4_compressor.o build/debug/core/exception_hacks.o build/debug/core/future-util.o -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s  -lyaml-cpp -lcares-seastar -lfmt -lasan -lubsan  
/usr/bin/x86_64-linux-gnu-ld: build/debug/libcares-seastar.a(ares_destroy.c.o): relocation R_X86_64_PC32 against symbol `ares_free' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

I added `set (CMAKE_POSITION_INDEPENDENT_CODE TRUE)` at the start of `c-ares/CMakeLists.txt` as well, building finished without any more errors, but when I tried to compile and run simple apps they just kept crashing in random places, e.g. in `fmt::internal::WidthHandler::report_unhandled_arg()`. Looks like I violated ODR somehow with my naive hacking.

**Comment by denesb** [comment]
If I recall correctly we don't support building seastar as a shared library.

**Comment by shadeware** [comment]
That's too bad, my app must be a pluggable module (.so). 
By the way, I learned about this flag in [README-OSv.md](https://github.com/scylladb/seastar/blob/master/README-OSv.md) (not that I'm targeting OSv, I just tried to gather as much info as possible).

**Comment by nyh** [comment]
On Tue, Jun 19, 2018 at 3:23 PM, Botond Dénes <notifications@github.com>
wrote:

> On 2018-06-19 15:20, shadeware wrote:
> > That's too bad, my app must be a pluggable module (.so).
> > By the way, I learned about this flag in [README-OSv.md](https://
> github.com/scylladb/seastar/blob/master/README-OSv.md) (not that I'm
> targeting OSv, I just tried to gather as much info as possible).
> >
>
> I might be wrong but you can still build a shared library app and link
> libseastar.a into it.
>
> I think README-OSv.md is outdates as a whole but I'm not sure about
> that, @nyh can tell you more about that.
>

Yes, README-OSv.md is outdated (OSv support in Seastar was removed piece by
piece, and
now only small pieces actually remain). But it does explain what "--so" is
trying to do:
It doesn't only compile Seastar itself as a shared object libseastar.so
instead of libseastar.a. Rather
it compiles also the example applications as shared objects, and this is
where you saw the problem.

I think this mode of compilation fit exactly what you're trying to do
(building a shared object which
includes both Seastar and your application), and it exposes real bugs in
our build scripts which are
not only crazy-complex, but now we even have two of them, and I can no
longer keep track which
one has which bugs :-( I think we need to fix those bugs.

Finally, one comment:
I don't know why you're trying to build a Seastar application as .so, but
if it's because you want
to run it alongside "normal" (non-Seastar) code, you'll have various
problems. One is that
Seastar will try, by default, to fill all the memory and CPU. Another is
that Seastar redefines
malloc() in a way which may break the non-Seastar code. The README-OSv.md
suggests
to use -DSEASTAR_DEFAULT_ALLOCATOR.

**Comment by shadeware** [comment]
Thank you for responses!

Linking libseastar.a to my .so doesn't seem to work. I can't tell exact linking flags since I'm using CMake and apparently there's nothing like compile_commands.json for linker, but when I try to add `-Wl,--whole-archive,/coding/seastar/build/debug/libcares-seastar.a,--no-whole-archive` to `TARGET_LINK_LIBRARIES` I get this compile-time error:
```
[13/13 0.5/sec] Linking CXX shared module libmod_myapp.so
FAILED: libmod_myapp.so
...
/usr/bin/x86_64-linux-gnu-ld: coding/seastar/build/debug/libcares-seastar.a(ares__close_sockets.c.o): relocation R_X86_64_PC32 against symbol `ares_free' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
and when I supply these flags to `${CMAKE_EXE_LINKER_FLAGS}` (like the rest of `pkg-config` flags) it builds just fine but fails to load with error
```
_myapp.so: undefined symbol: _ZN7seastar17g_current_contextE
```
(Apparently this is thread-local variable).

> Finally, one comment:
I don't know why you're trying to build a Seastar application as .so, but
if it's because you want
to run it alongside "normal" (non-Seastar) code, you'll have various
problems. 

Yep, I'm planning to use seastar alongside normal code (so that seastar will handle I/O and other async/performance-sensitive stuff and pass results to normal code), and I intend to use `-DSEASTAR_DEFAULT_ALLOCATOR` and `--overprovisioned`.

**Comment by avikivity** [comment]
Please also look at `seastar::alien`.

You'll need to adjust the c-ares configuration to have it produce relocatable core (-fpic). Alternatively, teach ./configure.y to use the system libcares.so instead of the bundled sources, if your system carries a new-enough version of c-ares.

**Comment by shadeware** [comment]
It actually worked! I did the following steps:

1) add `set (CMAKE_POSITION_INDEPENDENT_CODE TRUE)` at the start of `c-ares/CMakeLists.txt`
2) configure seastar with `-fPIC` (e.g. `./configure.py --disable-hwloc --cflags="-DSEASTAR_DEFAULT_ALLOCATOR -fPIC"`)
3) ninja
4) copy pkg-config's compile flags to CMAKE_CXX_FLAGS
5) copy libs from pkg-config's linker flags to CMake's `TARGET_LINK_LIBRARIES` arguments (not `${CMAKE_EXE_LINKER_FLAGS}`)

So, my problem is resolved, but `--so` still remains in code and docs. Should I close this issue?

**Comment by denesb** [comment]
On 2018-06-19 19:57, shadeware wrote:
> It actually worked! I did the following steps:
> 
> 1) add `set (CMAKE_POSITION_INDEPENDENT_CODE TRUE)` at the start of `c-ares/CMakeLists.txt`
> 2) configure seastar with `-fPIC` (e.g. `./configure.py --disable-hwloc --cflags="-DSEASTAR_DEFAULT_ALLOCATOR -fPIC"`)
> 3) ninja
> 4) copy pkg-config's compile flags to CMAKE_CXX_FLAGS
> 5) copy libs from pkg-config's linker flags to CMake's `TARGET_LINK_LIBRARIES` arguments (not `${CMAKE_EXE_LINKER_FLAGS}`)
> 
> So, my problem is resolved, but `--so` still remains in code and docs. Should I close this issue?
> 

The issue is still valid, to close it we should either:
1) Make --so work properly.
2) Remove it from configure.py and the docs.

As it looks like there is interest in this (1) would be preferred.

**Comment by tchaikov** [comment]
so support was added in #1484.
